### ISSUE TITLE
Pod mac is added into the podMap instead of VMMap

### ISSUE THREAD

**Issue by nikita133** [K8sNetworkPlumbingWG/kubemacpool#14]
Scenario:
Step 1:Create VM with more the 2 or 3 interfaces bridged to Linux Bridge.
Step 2:Turn on this VM
Step 3: Check that mac allocated from default mac pool
Step 4: Shrink mac pool and restart kubemacpool-mac-controller-manager pod
Step 5: Check logs.
Issue is below:

Data	{"macmap": {"02:00:00:00:00:05":"Allocated","02:00:00:00:00:06":"Allocated"}, "podmap": {"myproject/virt-launcher-vmtest-m9hxg":{"br1":"02:00:00:00:00:05","br2":"02:00:00:00:00:06"}}, "vmmap": {}, "currentMac": "02:00:00:00:00:00"}

its add the pod into the podMap and not under the vmMap

**Comment by SchSeba** [comment]
Closed by #13
