### ISSUE TITLE
Mac re-usage doesn't work. 

### ISSUE THREAD

**Issue by nikita133** [K8sNetworkPlumbingWG/kubemacpool#17]
Scenario:
Step 1: Create mac-pool with 3 available addresses
Step 2: Add VM_A with 3 interfaces 
Step 3: Check that 2 mac addresses were allocated to the new VM's interfaces 
Step 4: Try to add VM_B with 3 interfaces. Make sure that step is failed due to MAC starvation.
Step 5: Delete VM_A and make sure that 2 mac addresses were released
Step 6: Try to recreate VM_B. The step is failed due to bug.
Issue: Mac re-usage doesn't work . Released mac doesn't available for re assignment

**Comment by SchSeba** [comment]
closed by #18
